name: Deploy to Chromatic on Test Acceptance

on:
  push:
    branches:
      - test/acceptance

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or the version you are using

    - name: Install dependencies
      run: npm install

    - name: Publish to Chromatic
      env:
        CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      run: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
